version: '3.8'
services:
  ttlinkedinprofiletaker:
    build:
      context: .
      dockerfile: src/TTLinkedinProfileTaker/Dockerfile
    ports:
      - "8080:8080"
    image: ttlinkedinprofiletaker
    container_name: tt-linkedin-profile-taker
    depends_on:
      - selenium
  selenium:
    image: selenium/standalone-chrome
    container_name: selenium
    ports:
      - "4444:4444"
